go: why go should be the next enterprise programming language
dwarvesf/playground pull request #363
Opened 2024-09-13 08:24 UTC by thangnt294

#### What's this PR do?

- [x] Add a writing on why go should be the next enterprise programming language

2024-09-13 08:45 UTC, fuatto commented
lgtm, but should we at the context of how Google struggled and came up with using Go to solve it, maybe a bit of a history context in the beginning would be convincing, found a cool ref: https://github.com/golang-design/history
@thangnt294

2024-09-16 03:55 UTC, fuatto approved these changes

2024-09-16 04:52 UTC, zlatanpham requested changes
An update is needed to add recommendations for scenarios in which Go can replace and be a better choice than Java. I think this is a key point in the report, but it’s not easily understood after a quick skim.

2024-09-16 09:23 UTC, zlatanpham approved these changes

2024-09-16 09:23 UTC, zlatanpham commented on go/why-go.md
> +#### Citations
```suggestion
### Citations
```

2024-09-16 09:24 UTC, merged